const fs = require("fs");
const content = [
  '"use client";',
  "",
  'import { useEffect, useState } from "react";',
  'import { useParams } from "next/navigation";',
  'import DashboardLayout from "../components/DashboardLayout";',
  "",
  "type UserData = {",
  "  name: string;",
  "  email: string;",
  "  avatar?: string;",
  "};",
  "",
  "export default function DashboardSlugPage() {",
  "  const params = useParams();",
  "  const [user, setUser] = useState<UserData | null>(null);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  '    if (typeof window === "undefined") return;',
  '    const u = localStorage.getItem("sd_user");',
  "    if (!u) {",
  '      setUser({ name: "Guest", email: "guest@smartdocs.ai" });',
  "      setLoading(false);",
  "      return;",
  "    }",
  '    setUser({ name: u.includes("@") ? u.split("@")[0] : u, email: u });',
  "    setLoading(false);",
  "  }, []);",
  "",
  "  if (loading) {",
  "    return (",
  '      <div className="flex min-h-screen items-center justify-center bg-gray-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">',
  '        <div className="rounded-3xl bg-white px-6 py-4 shadow-lg ring-1 ring-black/5 dark:bg-slate-900">',
  "          Loading...",
  "        </div>",
  "      </div>",
  "    );",
  "  }",
  "",
  "  if (!user) return null;",
  "",
  "  return (",
  "    <DashboardLayout user={user} />",
  "  );",
const target = "c:/Users/Sujeet/Desktop/my-app/frontend/app/dashboard/[slug]/page.tsx";
fs.writeFileSync(target, content, "utf8");
console.log("Written successfully to " + target);
