CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  employeeCode VARCHAR(50) UNIQUE NOT NULL,
  designation VARCHAR(255) DEFAULT NULL,
  department VARCHAR(255) DEFAULT NULL,
  dateOfJoining DATE DEFAULT NULL,
  salary DECIMAL(10, 2) DEFAULT NULL,
  status ENUM('active', 'inactive', 'terminated') DEFAULT 'active',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

