import { PlanId } from "@/lib/plan-config";

export type ServiceCategory = "PDF & Documents" | "AI Chat" | "Translation" | "OCR & Images" | "Data & Tables" | "Conversion" | "Live Information" | "Family Guardian";
export type ImplementationStatus = "IMPLEMENTED" | "PARTIALLY_IMPLEMENTED" | "NOT_IMPLEMENTED" | "DEPRECATED";

export interface SmartDocsService {
  name: string;
  category: ServiceCategory;
  description: string;
  input: string;
  output: string;
  supportedFileTypes: string[];
  supportedLanguages: string[];
  requiredPlan: PlanId | "All plans";
  requiredFeatureFlag: string;
  creditUsage: string;
  existingApiTool: string;
  implementationStatus: ImplementationStatus;
  exampleUserRequests: string[];
}

export const SMARTDOCS_SERVICES: SmartDocsService[] = [
  // ... (existing services)
  {
    name: "General AI Chat",
    category: "AI Chat",
    description: "Provides answers to general knowledge questions, helps with writing tasks (emails, reports), and engages in conversation when no specific document or tool is required.",
    input: "A user query (string).",
    output: "A text answer generated by the AI model.",
    supportedFileTypes: ["N/A"],
    supportedLanguages: ["English", "Hindi", "Spanish", "French", "German"],
    requiredPlan: "All plans",
    requiredFeatureFlag: "AI_CHAT",
    creditUsage: "1 credit per message. Free plan: limited daily.",
    existingApiTool: "generateAIResponse (default path in orchestrator)",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "What is cloud computing?",
      "Write an email to my manager asking for a day off.",
      "Hello, how are you?",
      "Mere plan mein kya kya services hain?",
    ],
  },
  {
    name: "Document Q&A",
    category: "PDF & Documents",
    description: "Answers user questions based on the content of a specific, uploaded document.",
    input: "A user query (string) and a document ID.",
    output: "A text answer grounded in the document's content, with page citations.",
    supportedFileTypes: ["PDF"],
    supportedLanguages: ["English", "Hindi", "Spanish", "French", "German"],
    requiredPlan: "basic",
    requiredFeatureFlag: "DOCUMENT_AI",
    creditUsage: "2 credits per question.",
    existingApiTool: "DocumentQATool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "What does page 5 say about revenue?",
      "Find the section on market analysis in this document.",
      "Is dastaavez mein mukhya nishkarsh kya hain?",
    ],
  },
  {
    name: "Document Summarization",
    category: "PDF & Documents",
    description: "Creates a concise summary of the content retrieved from an uploaded document.",
    input: "A user request for a summary and a document ID.",
    output: "A text summary of the document's content.",
    supportedFileTypes: ["PDF"],
    supportedLanguages: ["English", "Hindi", "Spanish", "French", "German"],
    requiredPlan: "pro",
    requiredFeatureFlag: "DOCUMENT_AI",
    creditUsage: "3 credits per summary request.",
    existingApiTool: "DocumentSummarizationTool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "Summarize this PDF.",
      "Give me the key points of this report.",
      "Is PDF ka saaransh banao.",
    ],
  },
  {
    name: "Document OCR (Image & PDF Text Extraction)",
    category: "OCR & Images",
    description: "Extracts text from uploaded images and scanned PDF documents.",
    input: "An image or PDF file.",
    output: "Extracted text from the document.",
    supportedFileTypes: ["JPG", "PNG", "WEBP", "PDF"],
    supportedLanguages: ["English", "Hindi", "Spanish", "French", "German"],
    requiredPlan: "basic",
    requiredFeatureFlag: "OCR",
    creditUsage: "2 credits per page.",
    existingApiTool: "DocumentOCRTool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "Extract text from this image.",
      "Can you read the text in this photo?",
      "PDF se text extract karo.",
    ],
  },
  {
    name: "Document Conversion",
    category: "Conversion",
    description: "Converts uploaded PDF documents into TXT, DOCX, or XLSX format.",
    input: "A document ID and target format (txt, docx, xlsx).",
    output: "A downloadable converted file stored in B2 with a signed URL.",
    supportedFileTypes: ["PDF"],
    supportedLanguages: ["English"],
    requiredPlan: "pro",
    requiredFeatureFlag: "DOCUMENT_CONVERSION",
    creditUsage: "0 credits (non-AI operation)",
    existingApiTool: "DocumentConversionTool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "Convert this PDF to Word.",
      "Convert this PDF to text.",
      "Make this PDF into an editable Word document.",
      "Extract the table and create Excel.",
    ],
  },
  {
    name: "Document Translation",
    category: "Translation",
    description: "Translates the content of an entire document from a source language to a target language.",
    input: "A document ID and target language.",
    output: "A translated version of the document or its text.",
    supportedFileTypes: ["PDF"],
    supportedLanguages: ["English", "Hindi", "Spanish", "French", "German"],
    requiredPlan: "pro_plus",
    requiredFeatureFlag: "DOCUMENT_TRANSLATION",
    creditUsage: "Varies by document size (5 credits per page).",
    existingApiTool: "DocumentTranslationTool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
      "Translate this PDF to English.",
      "Is dastaavez ka Spanish mein anuvaad karein.",
      "Can you translate my PDF?",
    ],
  },
  {
    name: "Family Guardian Action",
    category: "Family Guardian",
    description: "Manages Family Guardian settings, such as blocking/allowing apps or websites for a child.",
    input: "A user query (string) like 'Block YouTube for an hour for Rahul'.",
    output: "A confirmation prompt and an action payload to be executed.",
    supportedFileTypes: ["N/A"],
    supportedLanguages: ["English"],
    requiredPlan: "pro_plus",
    requiredFeatureFlag: "FAMILY_GUARDIAN_ACCESS",
    creditUsage: "1 credit per action.",
    existingApiTool: "FamilyGuardianActionTool",
    implementationStatus: "IMPLEMENTED",
    exampleUserRequests: [
        "Block YouTube for an hour for Rahul.",
        "Allow Instagram for an hour for Sarah.",
        "Unblock roblox for 30 minutes for John."
    ],
  }
];
